name: Shell Commands
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "my first github job"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run -windows-commands:
    runs-on: windows-latest
    steps:
      - name: directory powershell
        run: Get-Location
      - name: directory bash
        run: pwd
        shell: bash  