name: Shell Commands
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "my first github job"
      - name: multiline script
        run: |
          node -v
          npm -v